import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initNumbers from "./modules/numbers.js";
import initTabNav from "./modules/initTabNav.js";
import initMobileMenu from "./modules/mobileMenu.js";
import openingHours from "./modules/openingHours.js";
import initAccordion from "./modules/initiAccordion.js";
import initScrollSuave from "./modules/scrollSuave.js";
import initDropdownMenu from "./modules/dropdownMenu.js";
import animationOnScroll from "./modules/animationOnScroll.js";

initModal();
initTabNav();
initTooltip();
initNumbers();
openingHours();
initAccordion();
initMobileMenu();
initScrollSuave();
initDropdownMenu();
animationOnScroll();
