services:
  node:
    build: 
      context: .
      target: prod
    ports:
      - '3040:3000'
    env_file:
      - .env
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"
      restart: unless-stopped
      stop_grace_period: 10s 

  caddy:
    image: caddy:alpine
    ports:
      - '80:80'
    volumes:
      - ./front:/usr/share/caddy

