services:
  node:
    build: 
      context: .
      target: prod
    ports:
      - '3040:3000'
   

  caddy:
    image: caddy:alpine
    ports:
      - '80:80'
    volumes:
      - ./front:/usr/share/caddy

